language: cpp
compiler:
  - clang
  - gcc

before_install:
  - cmake --version

script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DGDCM_ALLOW_INSOURCE_BUILD:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DBUILDNAME:STRING=${TRAVIS_OS_NAME}-${TRAVIS_BRANCH} ..
  - ctest -D ExperimentalStart
  - ctest -D ExperimentalBuild -V
  - ctest -D ExperimentalTest -j2 || true
  - ctest -D ExperimentalSubmit || true
