version: 2.7.0.{build}

environment:
  matrix:
  - config: RelWithDebInfo

# Operating system (build VM template)
os: Visual Studio 2015

platform: ARM
#  - x86
#  - x64
#  - ARM

# scripts that are called at very beginning, before repo cloning
init:
  # Print environment info
  - set
  - msbuild /version
  - cmake --version
  - python --version
  - java -version

#- call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
#- cl

# scripts that run after cloning repository
#install:
#  - cd c:\projects\gdcm
#  # Fetch submodules
#  - git submodule update --init --recursive

#before_build:
#  - cmake -H. -BBuild/VS -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM% -Wno-dev

build_script:
  - cd c:\projects\gdcm
  - mkdir build
  - cd build
  - echo %config%
  - cmake -Wno-dev -G "Visual Studio 14 Win64" -DCMAKE_BUILD_TYPE=%config% -DGDCM_BUILD_TESTING:BOOL=ON -DGDCM_BUILD_APPLICATIONS:BOOL=ON -DGDCM_BUILD_SHARED_LIBS:BOOL=ON -DGDCM_ALLOW_INSOURCE_BUILD:BOOL=ON -DBUILDNAME:STRING=%COMPUTERNAME%-%config% ..
  # msbuild /m => parallel
  #- msbuild gdcm.sln /m /p:Configuration=%config% /toolsversion:14.0 /p:Platform=x64 /p:PlatformToolset=v140
  - ctest -D ExperimentalStart
  - ctest -D ExperimentalBuild -V
  #  NUMBER_OF_PROCESSORS=2
  - ctest -D ExperimentalTest -j2 -C %config%
  - ctest -D ExperimentalSubmit

#build:
#  project: Build\VS\GDCM.sln
#  parallel: true
#  verbosity: minimal
