version: 2.7.0.{build}

environment:
  matrix:
  - config: RelWithDebInfo

shallow_clone: true

# Operating system (build VM template)
os: Visual Studio 2015

platform: x64

install:
  - set
  - cmake --version

before_build:
  - cmake -H. -BBuild/VS -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM% -Wno-dev

build:
  project: Build\VS\GDCM.sln
  parallel: true
  verbosity: minimal
